os: osx
branches:
  only:
    - chore/ci
before_install:
  - mkdir source
  - mv *[^source]* source
  - wget https://developer.elgato.com/documentation/stream-deck/distributiontool/DistributionToolMac.zip
  - unzip DistributionToolMac.zip
script:
  - ls -a
